spring:
  banner:
    image:
      location: classpath:banner.txt
  data:
    mongodb:
      port: 27981
      database: vendasdb
      
camel:
  springboot:
    main-run-controller: true
    jmx-enabled: false
    
route:
  basePath: data
  pathFrom: ${route.basePath}/in
  pathTo: ${route.basePath}/out
  from: file://${route.pathFrom}?autoCreate=true&delay=1000&moveFailed=../../${route.pathTo}/error
  to: file://${route.pathTo}?autoCreate=true
